apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: patient-service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: laerkeimeland/patient-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "Server=mysql-server,3306;Database=BloodPressureTrackerDb;Uid=root;Pwd=MyStrong!Passw0rd;"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: patient-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: patient-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

