name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List files # To make sure the path for the .csproj files are correct
      run: |
        ls -R

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0' 

    - name: Restore dependencies for PatientService
      run: dotnet restore PatientService/PatientService.csproj

    - name: Restore dependencies for MeasurementService
      run: dotnet restore MeasurementService/MeasurementService.csproj

    - name: Build PatientService
      run: dotnet build PatientService/PatientService.csproj --no-restore

    - name: Build MeasurementService
      run: dotnet build MeasurementService/MeasurementService.csproj --no-restore

# No tests

  dockerize:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image for PatientService
    - name: Build Docker image for PatientService
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/patient-service:latest -f PatientService/Dockerfile .

    # Build Docker image for MeasurementService
    - name: Build Docker image for MeasurementService
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/measurement-service:latest -f MeasurementService/Dockerfile .

    # Push PatientService Docker image
    - name: Push Docker image for PatientService
      run: docker push ${{ secrets.DOCKER_USERNAME }}/patient-service:latest

    # Push MeasurementService Docker image
    - name: Push Docker image for MeasurementService
      run: docker push ${{ secrets.DOCKER_USERNAME }}/measurement-service:latest

#´No deploy server